apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-test-pv
  namespace: kubeflow-user-example-com
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/captcha-test-pv/captcha-test"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-test-pv-claim
  namespace: kubeflow-user-example-com
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
